spring.application.name=ai-avatar-backend
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/avatar_saas
spring.datasource.username=avatar_admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379


tts.provider=cartesia
openrouter.api-key=${OPENROUTER_API_KEY}
cartesia.api-key=${CARTESIA_API_KEY}
seedance.api-key=${SEEDANCE_API_KEY}
sync.api-key=${SYNC_API_KEY}
pixazo.api-key=${PIXAZO_API_KEY}


file.storage.audio-path=storage/audio
file.storage.avatar-path=storage/avatars
file.storage.avatar-video-path=storage/avatar-videos
file.storage.scene-video-path=storage/scene-videos

elevenlabs.api-key=${ELEVENLABS_API_KEY}

