spring.application.name=ai-avatar-backend

server.port=${PORT:8081}

# PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Redis
# Redis
spring.data.redis.url=${REDIS_URL}

# AI Providers
tts.provider=cartesia

openrouter.api-key=${OPENROUTER_API_KEY}
cartesia.api-key=${CARTESIA_API_KEY}
seedance.api-key=${SEEDANCE_API_KEY}
sync.api-key=${SYNC_API_KEY}
pixazo.api-key=${PIXAZO_API_KEY}
elevenlabs.api-key=${ELEVENLABS_API_KEY}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# File Storage
file.storage.audio-path=storage/audio
file.storage.avatar-path=storage/avatars
file.storage.avatar-video-path=storage/avatar-videos
file.storage.scene-video-path=storage/scene-videos
